#! /usr/bin/env bash

if [ "${1}" = "" ]; then
  cat << EOF
Usage: ${0} KVER

where:
  KVER      kernel version to build against (e.g. 3.19)
EOF
  exit 123
fi

KVER=${1}

get_master_sources() {
  wget -O master.tar.gz https://github.com/torvalds/linux/tarball/master
  tar -xzf master.tar.gz
  echo $(pwd)/torvalds-linux-*
}

get_tagged_sources() { # version
  wget "https://github.com/torvalds/linux/archive/v${1}.tar.gz"
  tar -xzf "v${1}.tar.gz"
  echo "$(pwd)/linux-${1}"
}

prepare_kernel() { # srcDir
  oldDir=$(pwd)

  cd "${1}"
  make olddefconfig
  make prepare
  make scripts
  make kernel

  cd "${oldDir}"
}

if [ "${KVER}" = "master" ]; then
  srcDir=$(get_master_sources)
else
  srcDir=$(get_tagged_sources "${KVER}")
fi

prepare_kernel "${srcDir}"
make KDIR="${srcDir}" CC=${CC:-gcc}

