#! /usr/bin/env bash

set -e
set -u

files=(
  checkpatch.pl
  const_structs.checkpatch
  spelling.txt
)

for file in ${files[@]}; do
  wget -N -q "https://raw.githubusercontent.com/torvalds/linux/master/scripts/${file}"
done

chmod +x checkpatch.pl

./checkpatch.pl --terse --no-tree --ignore NEW_TYPEDEFS -f ./library/*
./checkpatch.pl --terse --no-tree --ignore LINUX_VERSION_CODE,PREFER_PR_LEVEL -f ./module/*

rm ${files[@]}
